name: Rust

on:
  push:
    tags:
      - 'v*'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Cross-Compile Toolchain
      run: |
        sudo apt-get update
        # Installiamo il compilatore MinGW per Windows
        sudo apt-get install -y mingw-w64 pkg-config

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        # Aggiungiamo il "bersaglio" Windows
        targets: x86_64-pc-windows-gnu

    - name: Build for Windows
      # Specifichiamo il target Windows durante il build
      run: cargo build --release --target x86_64-pc-windows-gnu --verbose

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: RPGMDec
        # Il percorso cambia perché Rust mette i file in una cartella specifica per il target
        path: target/x86_64-pc-windows-gnu/release/rpgmdec.exe