name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  CFLTK_MSVC_CRT_STATIC: OFF

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build
      # Aggiungiamo flag specifici per ignorare i warning che bloccano la build
      run: cargo build --release --verbose
      env:
        CFLAGS: "-nologo -MD"
        CXXFLAGS: "-nologo -MD"

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: programma-windows
        path: target/release/rpgmdec.exe
